name: Pytest

on: [push]

jobs:
  test_setup:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]
    steps:
    - uses: actions/checkout@v3
    - name: Get cmake
      uses: threeal/cmake-action@v1.3.0
    - name: build application
      run: |
        cmake -B build
        make -C build
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

  test_p1:
    runs-on: ubuntu-latest
    needs: test_setup
    steps:
    - name: Run tests
      uses: dariocurr/pytest-summary@main
      with:
       paths: test/test_praxis1.py
       options: --quiet 
       show: all

  test_p2:
    runs-on: ubuntu-latest
    needs: [test_setup, test_p1]
    steps:
    - name: Run tests
      uses: dariocurr/pytest-summary@main
      with:
       paths: test/test_praxis2.py
       options: --quiet 
       show: all
    
